name: Frontend Updates runner

on:
  push:
    branches:
      - main
    paths:
      - "packages/frontend-updates-runner/**"
      - ".github/workflows/frontend-updates-runner.yml"

jobs:
  frontend-updates-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run frontend updates runner
        env:
          ENV_GITHUB_APP_ID: ${{ secrets.ENV_GITHUB_APP_ID }}
          ENV_GITHUB_PRIVATE_KEY: ${{ secrets.ENV_GITHUB_PRIVATE_KEY }}
        run: npx tsx packages/frontend-updates-runner/src/udapte-depency-in-repos.ts
